import { it, expect } from "vitest";
import { createApp } from "./app.js";
import { SceneManager } from "../core/sceneManager.js";
import { createStorage } from "../core/storage.js";
import { levels } from "../levels/levels.js";
import { Pause } from "./Pause.js";
import { Result } from "./Result.js";
it("routes menus, freezes gameplay under pause and records results before next level", () => {
  const manager = new SceneManager();
  const app = createApp(manager, createStorage());
  app.title();
  manager.current.buttons[0].action();
  expect(manager.current.buttons[1].disabled).toBe(true);
  manager.current.buttons[0].action();
  const game = manager.current;
  game.drag = { pointerId: 1 };
  game.onKeyDown("p");
  expect(manager.current).toBeInstanceOf(Pause);
  expect(game.drag).toBeNull();
  manager.update(1);
  expect(game.elapsed).toBe(0);
  manager.current.onKeyDown("escape");
  expect(manager.current).toBe(game);
  game.onHidden();
  manager.current.buttons[0].action();
  game.score = 20;
  game.remainingArrows = 0;
  game.finishIfReady();
  expect(manager.current).toBeInstanceOf(Result);
  expect(app.storage.getProgress().unlocked).toBe(2);
  manager.current.buttons.find((b) => b.label === "下一關").action();
  expect(manager.current.level).toBe(levels[1]);
  app.finish(levels[4], { score: 0, stars: 0, maxScore: 50, accuracy: 0 });
  expect(manager.current.buttons).toHaveLength(2);
  app.select();
  expect(manager.scenes).toHaveLength(1);
});
it("activates a button only on release inside with the original pointer", () => {
  const manager = new SceneManager();
  const app = createApp(manager, createStorage());
  app.title();
  const title = manager.current;
  title.onPointerDown({ x: 400, y: 250, buttons: 1, pointerId: 1 });
  title.onPointerUp({ x: 400, y: 250, pointerId: 2 });
  expect(manager.current).toBe(title);
  title.onPointerUp({ x: 0, y: 0, pointerId: 1 });
  expect(manager.current).toBe(title);
  title.onPointerDown({ x: 400, y: 250, buttons: 1, pointerId: 1 });
  title.onPointerUp({ x: 400, y: 250, pointerId: 1 });
  expect(manager.current).not.toBe(title);
});
